### ISSUE TITLE
REST API请求因遇到了错误而失败。（cURL error 28）

### ISSUE THREAD

**Issue by YuMXuan** [stevenjoezhang/mimi-captcha#1]
![image](https://user-images.githubusercontent.com/33976251/65322052-56f7a580-dbd8-11e9-90bb-0b61489d909e.png)
这个插件会造成以下错误：
cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received

这是我的站点信息：

### wp-core ###

version: 5.2.3
site_language: zh_CN
user_language: zh_CN
permalink: /%year%/%monthnum%/%day%/%post_id%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 252.24 MB (264494407 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 491.99 KB (503795 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 3.06 MB (3209091 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 68.31 MB (71625291 bytes)
database_size: 2.94 MB (3080192 bytes)
total_size: 327.03 MB (342912776 bytes)

### wp-active-theme ###

name: Twenty Nineteen
version: 1.4
author: WordPress团队
author_website: https://cn.wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, infinite-scroll, jetpack-responsive-videos, jetpack-geo-location, jetpack-content-options, widgets
theme_path: /var/www/html/wp-content/themes/twentynineteen

### wp-themes (2) ###

Twenty Seventeen: version: 2.2, author: WordPress团队
Twenty Sixteen: version: 2.0, author: WordPress团队

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.7.0

### wp-plugins-active (11) ###

Akismet Anti-Spam: version: 4.1.2, author: Automattic
Beaver Builder Plugin (Lite Version): version: 2.2.4.3, author: The Beaver Builder Team
Better Notifications for WP: version: 1.7.4, author: Made with Fuel
Elementor: version: 2.7.2, author: Elementor.com
Health Check & Troubleshooting: version: 1.4.0, author: The WordPress.org community
Jetpack by WordPress.com: version: 7.7.1, author: Automattic
Mimi Captcha: version: 0.1.1, author: Shuqiao Zhang
Really Simple SSL: version: 3.2.5, author: Rogier Lankhorst, Mark Wolters
Shortcodes Ultimate: version: 5.4.1, author: Vladimir Anokhin
WP Mail SMTP: version: 1.6.2, author: WPForms
WP User Avatar: version: 2.2.4, author: flippercode

### wp-plugins-inactive (1) ###

AMP: version: 1.2.2, author: AMP Project Contributors

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 x86_64 2019-06-15 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 4 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 4 GB
	imagick::RESOURCETYPE_MEMORY: 2 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.4.0-164-generic x86_64
httpd_software: nginx/1.17.3
php_version: 7.3.9-1+ubuntu16.04.1+deb.sury.org+1 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.47.0 OpenSSL/1.0.2g
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 5.7.27-0ubuntu0.16.04.1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

**Comment by stevenjoezhang** [comment]
收到，我研究一下

**Comment by stevenjoezhang** [comment]
https://github.com/WordPress/WordPress/blob/6ca808129cbbcc2b4a2bd2fb777997bbc4e45fcd/wp-admin/includes/class-wp-site-health.php#L1696-L1716

**Comment by stevenjoezhang** [comment]
找到一个相关的帖子了：https://wordpress.org/support/topic/does-not-play-well-with-php-sessions/

看上去很多需要用到session的验证码插件都会遇到这个问题，例如 https://wordpress.org/plugins/captcha-bank/
如果确实比较在意这个站点健康的话，可以暂时用google recaptcha代替。

**Comment by stevenjoezhang** [comment]
已在0.2.0版本修复
