### ISSUE TITLE
php报错

### ISSUE THREAD

**Issue by endfish** [stevenjoezhang/mimi-captcha#12]
Warning: Undefined array key "page" in /wp-content/plugins/mimi-captcha/mimi-captcha.php on line 178

WordPress 6.0
PHP版本 8.0.18

**Comment by endfish** [comment]
看了一下, 是因为PHP8.0对$GET要求更严格了.. 
如果看不惯报错的, 直接把这行改一下加个判断就行了
栗子:
`if (isset($_GET['page']) && $_GET['page'] === 'micaptcha_slug' && function_exists('admin_url')) {`

**Comment by stevenjoezhang** [comment]
谢谢反馈，我自己的网站还在用 WordPress 5 + PHP 7😂 我升级了测试一下

**Comment by stevenjoezhang** [comment]
代码已更新 https://github.com/stevenjoezhang/mimi-captcha/commit/7f4a28198fe7e8ec1d89ad790c76493bc1fcc232
