### ISSUE TITLE
希望可以增加对自定义字段的支持。

### ISSUE THREAD

**Issue by nonozone** [stevenjoezhang/mimi-captcha#13]
因为目前所用的模板使用了第三方开发的一套 问答插件。在minicaptcha后台，就没有这个位置的开关显示。

**Comment by stevenjoezhang** [comment]
这个自定义字段有统一的格式吗？目前的评论系统验证码是通过 `add_action` 和 `add_filter` 的 Hook 实现的

https://github.com/stevenjoezhang/mimi-captcha/blob/a4488b0612a3750e43faf1ae8e0eca541cc74632/mimi-captcha.php#L463-L477

如果问答插件也支持类似的 Hook，那么改一下代码就能支持验证码

**Comment by nonozone** [comment]
https://www.nonopen.com/question   这个地址哈...  

刚好这两天被人群发攻击，所以提交和恢复都要审核了。

**Comment by stevenjoezhang** [comment]
忘记回复了……这个我不太好做，我不知道你说的这个第三方开发的一套 问答插件的代码是咋样的。你看看有没有别的验证码插件可以支持。
