### ISSUE TITLE
这个插件是不是对PHP8支持不是很好，我明明已经启用了dg和mbstrin扩展，但是依然出错

### ISSUE THREAD

**Issue by nonozone** [stevenjoezhang/mimi-captcha#15]
/www.abc.com/%e8%b7%9f%e7%9d%80ai%e5%ad%a6flask.html"
2023/12/21 14:27:59 [error] 3644874#3644874: *99070 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_substr() in /srv/www/abc.com/public_html/wp-content/plugins/mimi-captcha/captcha.php:63
Stack trace:
#0 {main}
  thrown in /srv/www/abc.com/public_html/wp-content/plugins/mimi-captcha/captcha.php on line 63" while reading response header from upstream, client: 64.*.*.*, server: www.abc.com, request: "GET /wp-content/plugins/mimi-captcha/captcha.php?rand=0.5853143637758114 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.abc.com.sock:", host: "www.abc.com", referrer: "http://www.abc.com/%e8%b7%9f%e7%9d%80ai%e5%ad%a6flask.html"

**Comment by stevenjoezhang** [comment]
我自己的网站使用`PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)`没有遇到问题

**Comment by stevenjoezhang** [comment]
你可以检查 `php.ini` 文件或使用 `phpinfo()` 函数来确定是否启用了 mbstring 扩展。

**Comment by nonozone** [comment]
➜  ~ php -m |grep mbstring
mbstring  

是有的，只是我是安装的是php8.2-mbstring。
然后我也试了，apt install php-mbstring，问题依旧。

**Comment by stevenjoezhang** [comment]
很怪，试试重启一下`php-fpm`相关的守护进程？

**Comment by nonozone** [comment]
> 很怪，试试重启一下`php-fpm`相关的守护进程？

nginx，PHP都重启过了，甚至主机我都reboot了，都不行，主要是，现在确实也不知道从哪里排查，这个麻烦。

**Comment by stevenjoezhang** [comment]
那真的太不合理了，会不会是有多个版本冲突了，或者`php.ini`配置文件的问题？可以看看`phpinfo()`里面有没有`mbstring`

**Comment by nonozone** [comment]
哎，找到问题了，是因为我系统有两个php版本，我一直在调整php8的，没想到我网站配置文件，还在用php7...抱歉乌龙了。

**Comment by stevenjoezhang** [comment]
如果有其他问题欢迎继续讨论～
