### ISSUE TITLE
kratos主题评论表单无法显示

### ISSUE THREAD

**Issue by sammeishi** [stevenjoezhang/mimi-captcha#2]
使用的是kratos主题。登陆界面验证码正常显示，但是评论区底部不显示，源代码并没有插入验证码html。

**Comment by stevenjoezhang** [comment]
可以复现此问题，并找到了有关讨论： https://github.com/vtrois/kratos/issues/166
目前本插件只支持 WordPress 默认的评论，因为第三方的评论表单插件各不相同，适配成本较高。

**Comment by sammeishi** [comment]
> 可以复现此问题，并找到了有关讨论： [vtrois/kratos#166](https://github.com/vtrois/kratos/issues/166)
> 目前本插件只支持 WordPress 默认的评论，因为第三方的评论表单插件各不相同，适配成本较高。

刚粗略排查了下，comment_form_after_fields没被触发，换成comment_form就行了。 具体原因没深究，我提个PR你看下

**Comment by stevenjoezhang** [comment]
谢谢，我确认一下。`comment_form` 应该是一个在 WordPress 3.0 版本被弃用的 hook，可能刚好被 kratos 的评论表单采用了。见 https://github.com/stevenjoezhang/mimi-captcha/commit/a5f58cfe354d79c5200beb2fe260df7b704df9c4

**Comment by sammeishi** [comment]
> 谢谢，我确认一下。`comment_form` 应该是一个在 WordPress 3.0 版本被弃用的 hook，可能刚好被 kratos 的评论表单采用了。见 [a5f58cf](https://github.com/stevenjoezhang/mimi-captcha/commit/a5f58cfe354d79c5200beb2fe260df7b704df9c4)

OK
