### ISSUE TITLE
该插件在win系统上因字体文件夹为中文导致验证码无法正常显示

### ISSUE THREAD

**Issue by jonexyz** [stevenjoezhang/mimi-captcha#4]
在本地测试时发现验证码无法正常显示，最后通过分析发现是因为插件使用的字体的文件名为中文名，导致字体读取失败。即win系统字符集不是utf8所致。本人解决方法如下。
·// 判断当前获取文件名的字符集，并将该文件名转成utf8字符集
$encode = mb_detect_encoding($fontname, array("ASCII",'UTF-8',"GB2312","GBK",'BIG5'));
$fontname = mb_convert_encoding($fontname, 'UTF-8', $encode);·
![1453-3](https://user-images.githubusercontent.com/31957754/101270314-c7292180-37b2-11eb-87af-c89b7d7308df.jpg)

**Comment by jonexyz** [comment]
上面方法有问题，还是不要用中文文件名的好

**Comment by jonexyz** [comment]
找到具体问题所在了，因为win系统默认是gbk字符集，php代码是utf8字符集，在读取字体文件时，因路径存在中文，用utf8字符集的路径去读gbk字符集的文件名所以读取失败，因为我找不到可以获取系统字符集的方法，所以最好的解决方案还是在文件路径中不要用中文名

**Comment by stevenjoezhang** [comment]
我大意了，没考虑这个问题，所以是否需要将内置的这几个字体文件改为英文名，保证 windows 兼容性？
https://github.com/stevenjoezhang/mimi-captcha/tree/master/fonts

**Comment by jonexyz** [comment]
建议还是用英文名的好，避免不必要的bug出现

**Comment by stevenjoezhang** [comment]
我把`scandir`换成`glob`了： https://github.com/stevenjoezhang/mimi-captcha/commit/ac8d356d57e5733ec66762b0bbb4c3a70d3b553d
能否帮忙测试一下问题是否解决？

**Comment by jonexyz** [comment]
> 我把`scandir`换成`glob`了： [ac8d356](https://github.com/stevenjoezhang/mimi-captcha/commit/ac8d356d57e5733ec66762b0bbb4c3a70d3b553d)
> 能否帮忙测试一下问题是否解决？

抱歉，不常登录GitHub，建议还是不要用中文名的好，刚把本地环境的 wordpress 中的 Mimi Captcha 更新到了最新的版本 0.5.0 版本，因为插件自带的字体名是中文而无法显示，我把字体文件名改成数字或者英文就好了。

截图如下:  https://tva2.sinaimg.cn/mw690/b6559090gy1gskeaxnam3j21g50q4dkh.jpg

**Comment by jonexyz** [comment]
本地部署wordpress之后，发现你的插件字体文件名因为中文名的问题还是无法正常显示验证码，
我的本地环境：Windows 10 教育版，Mimi Captcha     0.6.0 版本

考虑兼容性的问题，建议还是不要使用中文文件名，以下截图仅为我的本地环境测试

![Snipaste_2024-01-30_09-20-16](https://github.com/stevenjoezhang/mimi-captcha/assets/31957754/2a07b0d6-f729-4bd1-b3f9-fc141c31cf48)
![Snipaste_2024-01-30_09-22-20](https://github.com/stevenjoezhang/mimi-captcha/assets/31957754/5b137b8d-3741-49b2-b65a-89604564abb8)

**Comment by stevenjoezhang** [comment]
谢谢反馈，这个确实也没啥好办法了😢，我重命名一下

**Comment by stevenjoezhang** [comment]
都改成英文了： https://github.com/stevenjoezhang/mimi-captcha/commit/522408a2ca0cb75a30ff52f53f2d1bc39a138cfa 我之后在WordPress插件库里面同步更新一下
