### ISSUE TITLE
Mimi Captcha导致REST API出现问题

### ISSUE THREAD

**Issue by AlphaRabbit21264** [stevenjoezhang/mimi-captcha#7]
问题详情：在安装并启用Mimi Captcha后，WordPress的站点健康检测一直会提示一个问题。

_session_start()函数调用生成了一个PHP会话。该会话干扰了REST API及环回请求。在做出任何HTTP请求前，该会话必须由session_write_close()函数关闭。_

操作系统：CentOS Linux 7.9
Web服务器：Nginx 1.21
PHP版本：7.3.28（带OpenRASP）
WordPress版本：5.7.2

**Comment by stevenjoezhang** [comment]
这个问题应该已经被修复了： 0ce4fcce7796a51bffbd0919df6e74789a93ae5e

**Comment by AlphaRabbit21264** [comment]
> 
> 
> 这个问题应该已经被修复了： [0ce4fcc](https://github.com/stevenjoezhang/mimi-captcha/commit/0ce4fcce7796a51bffbd0919df6e74789a93ae5e)

我复现一下，还是会
![图片](https://user-images.githubusercontent.com/42642334/124577880-46352400-de80-11eb-93be-e7650dbf86bb.png)

**Comment by stevenjoezhang** [comment]
试试更新一下插件，我昨天发布了0.5.0版本，在我的网站上测试是没有问题的

宝塔面板我不太熟，也可以试试暂时关闭PHP Session隔离功能，看看问题有没有解决

**Comment by AlphaRabbit21264** [comment]
> 试试更新一下插件，我昨天发布了0.5.0版本，在我的网站上测试是没有问题的
> 
> 宝塔面板我不太熟，也可以试试暂时关闭PHP Session隔离功能，看看问题有没有解决

问题已解决√
